### ISSUE TITLE
Errors when running train2D.py

### ISSUE THREAD

**Issue by MuhaoGuo** [jx-wang-s-group/ppnn#1]
Hi there, when I try to repeat the code, I meet an issue. Specifically,
1. I implemented the code data generation in` src/operators.py`, I get the data: `./burgers_test.pt`
2. I adjust the corresponding path variable `datafile `in `cases/burgers_fPDE.yaml`, then, I run `python src/train2D.py cases/burgers_fPDE.yaml`
3. _Error1_: in the following line, there is no 'u' index: 
`fdata:torch.Tensor = torch.load(params.datafile,map_location='cpu',)['u'][:,params.datatimestart:params.datatimestart+params.timesteps+1].detach().to(torch.float)[:] #dataonly` , 
so I just remove the `['u']`, and change this line to 
`fdata:torch.Tensor = torch.load(params.datafile,map_location='cpu',)[:,params.datatimestart:params.datatimestart+params.timesteps+1].detach().to(torch.float)[:] #dataonly`
5. When I run the ` train2D.py` again, I got the following _Error2_:
CFL: 4.5
Traceback (most recent call last):
  File "D:\Projects\ppnn\src\train2D.py", line 164, in <module>
    dataset = myset()
  File "D:\Projects\ppnn\src\train2D.py", line 125, in __init__
    pdeu = pde_du(data_u0.to(device), mus).cpu().half()
  File "D:\Projects\ppnn\src\train2D.py", line 76, in pde_du
    padBC_rd(dt*rhsu(u1,v1,mu,dudx,dudy,d2udx2,d2udy2,ux,uy,dx,dy,dx2,dy2))
  File "D:\Projects\ppnn\src\rhs.py", line 6, in burgers2DFu
    a = -u1*dudx(ux)/dx - v1*dudy(uy)/dy + mu*(d2udx2(ux)/dx2+d2udy2(uy)/dy2) + (1-uv)*u1+uv*v1
RuntimeError: The size of tensor a (21600) must match the size of tensor b (10000) at non-singleton dimension 0

Process finished with exit code 1

I guess it is causes by the dismatched size of "input data" with some variables in"train2D.py". I appreciate it if you can tell me how to fix the bugs, or maybe what data should I use to run the `python src/train2D.py cases/burgers_fPDE.yaml` Thanks a lot in advance.

**Comment by Xin-yang-Liu** [comment]
Hi Muhao, thanks for pointing this out. Yes, there is a mismatch with between the number of physical parameter: viscosity $\nu$ (`mu` in `train2D.py`) and the number of saved frames (`fdata` in the `train2D.py`). 

This issue is caused by the current data generation script in the `operators.py` is actually generating the testing set, which has 10000 snapshots (defined by L408 ~ L410 in `operators.py`), while the `mu` parameter is based on the yaml file (defined by L17 ~ L20 in the `burgers_fPDE.yaml`), which describing the training set. If you make them consistent with each other, this issue should be solved. 

I apologize for the confusion but I do not have time to thoroughly check and fix this code for now. I really appreciate it if you could create a pull request to fix it!
